const DEFAULT_API=window.CLIPNOVA_API_BASE||'';
const API=()=> (localStorage.getItem('clipnova_api')||DEFAULT_API).replace(/\/$/,'');
const $=s=>document.querySelector(s);
const url=$('#url'),status=$('#status'),preview=$('#preview'),progressCard=$('#progressCard'),apiInput=$('#apiInput');
let current=null;
function msg(t,good=false){status.textContent=t;status.style.color=good?'#63e6a8':''}
function fmtTime(sec){if(!sec)return '—';sec=Math.round(sec);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
async function paste(){try{url.value=await navigator.clipboard.readText();url.focus()}catch{msg('Không đọc được clipboard — hãy dán thủ công.')}}
async function inspect(){const v=url.value.trim();if(!v)return msg('Dán link trước nhé.');if(!API())return msg('Mở ⚙ và nhập URL backend trước.');msg('Đang phân tích…');preview.classList.add('hidden');try{const r=await fetch(API()+'/api/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:v})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Không phân tích được');current=j.data;$('#thumb').src=current.thumbnail||'';$('#title').textContent=current.title;$('#uploader').textContent=current.uploader||current.extractor||'';$('#duration').textContent=fmtTime(current.duration);$('#desc').textContent=current.description||'Không có mô tả.';const box=$('#formatBtns');box.innerHTML='';for(const h of (current.resolutions||[360,480,720,1080]).slice(-4)){const b=document.createElement('button');b.className='format';b.innerHTML=`🎬 ${h}p<small>MP4</small>`;b.onclick=()=>download('mp4',h);box.appendChild(b)}const mp=document.createElement('button');mp.className='format';mp.innerHTML='🎵 MP3<small>Audio</small>';mp.onclick=()=>download('mp3',0);box.appendChild(mp);preview.classList.remove('hidden');msg('Sẵn sàng tải ✓',true);preview.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){msg('❌ '+e.message)}}
async function download(type,height){if(!current)return;progressCard.classList.remove('hidden');$('#progressLabel').textContent=type==='mp3'?'Đang tạo MP3…':`Đang tải MP4 ${height}p…`;setProgress(0,'Đang xếp hàng');try{const r=await fetch(API()+'/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:current.webpage_url,type,height})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Không tạo được job');poll(j.job.id)}catch(e){setProgress(0,'❌ '+e.message)}}
function setProgress(p,t){$('#percent').textContent=Math.round(p)+'%';$('#barFill').style.width=Math.max(0,p)+'%';$('#progressMsg').textContent=t||''}
async function poll(id){const timer=setInterval(async()=>{try{const r=await fetch(API()+'/api/job/'+id);const j=await r.json();if(!j.ok)throw Error(j.error);setProgress(j.job.progress||0,j.job.message||j.job.status);if(j.job.status==='done'){clearInterval(timer);setProgress(100,'Hoàn tất ✓');const a=document.createElement('a');a.href=j.job.urlOut.startsWith('http')?j.job.urlOut:API()+j.job.urlOut;a.target='_blank';a.rel='noopener';a.click();loadHistory()}if(j.job.status==='error'){clearInterval(timer);setProgress(0,'❌ '+j.job.error)}}catch(e){clearInterval(timer);setProgress(0,'❌ '+e.message)}},900)}
async function loadHistory(){if(!API())return;try{const r=await fetch(API()+'/api/history');const j=await r.json();const box=$('#historyList');if(!j.items?.length){box.innerHTML='<div class="empty">Chưa có file nào.</div>';return}box.innerHTML=j.items.map(x=>`<div class="historyItem"><div class="hicon">${x.type==='mp3'?'🎵':'🎬'}</div><div><b>${escapeHtml(x.filename)}</b><small>${x.type.toUpperCase()} • ${new Date(x.createdAt).toLocaleString()}</small></div><a href="${x.url.startsWith('http')?x.url:API()+x.url}" target="_blank" rel="noopener">MỞ</a></div>`).join('')}catch{}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#pasteBtn').onclick=paste;$('#inspectBtn').onclick=inspect;$('#refreshHistory').onclick=loadHistory;
$('#settingsBtn').onclick=()=>{$('#settings').classList.add('open');apiInput.value=API()};$('#closeSettings').onclick=()=>$('#settings').classList.remove('open');$('#settings').onclick=e=>{if(e.target.id==='settings')$('#settings').classList.remove('open')};
$('#saveApi').onclick=()=>{const v=apiInput.value.trim().replace(/\/$/,'');if(v)localStorage.setItem('clipnova_api',v);else localStorage.removeItem('clipnova_api');$('#settings').classList.remove('open');msg(v?'Đã lưu backend ✓':'Đã xóa backend');loadHistory()};$('#resetApi').onclick=()=>{localStorage.removeItem('clipnova_api');apiInput.value='';msg('Đã xóa URL backend');loadHistory()};
url.addEventListener('keydown',e=>{if(e.key==='Enter')inspect()});loadHistory();
